#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service

SERVICE_NAME="restic-nginx-preloader"

modes=$(echo "${MODE}" | tr "," "\n")
for mode in $modes ; do
    case "${mode,,}" in
        "server" )
            ENABLE_SERVER=TRUE
        ;;
    esac
done

if [[ -z "${ENABLE_SERVER}" || "${ENABLE_SERVER,,}" != "true" ]]; then
    service_stop 10-nginx
    service_stop 11-nginx-config-reload
    rm -f \
            /container/init/init.d/10-nginx \
            /container/init/init.d/11-nginx-config-reload \
            /etc/zabbix/zabbix_agentd.conf.d/nginx.conf

fi

liftoff
