#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service
SERVICE_NAME="restic-nginx-preloader"

if [[ -z "${ENABLE_SERVER}" || "${ENABLE_SERVER,,}" = "false" ]]; then
    service_stop 10-nginx
    service_stop 11-nginx-config-reload
    rm -rf /etc/zabbix/zabbix_agentd.conf.d/nginx.conf
    rm -rf /container/init/init.d/10-nginx
    rm -rf /container/init/init.d/11-*
fi

liftoff
