services:
  restic-app:
    image: tiredofit/restic
    container_name: restic-app
    volumes:
      - ./cache:/cache
      - ./config:/config
      #- ./data:/repository
      - ./logs:/logs
      - /:/rootfs:ro
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=restic-app

      - MODE=BACKUP

      #- DEFAULT_REPOSITORY_PASS=password
      #- DEFAULT_REPOSITORY_PATH=/data/
      #- DEFAULT_REPOSITORY_PATH=rest:https://user:password@restic-server

      - BACKUP01_REPOSITORY_PATH=rest:https://user:password@restic-server/path1
      - BACKUP01_REPOSITORY_PASS=superduper
      - BACKUP01_SNAPSHOT_NAME=home
      - BACKUP01_SNAPSHOT_PATH=/rootfs/home
      - BACKUP01_SNAPSHOT_EXCLUDE=.snapshots,cache
      - BACKUP01_SNAPSHOT_TAG=important
      - BACKUP01_SNAPSHOT_BEGIN=1230
      - BACKUP01_SNAPSHOT_INTERVAL=60

      - BACKUP02_REPOSITORY_PATH=rest:https://user:password@restic-server/path2
      - BACKUP02_REPOSITORY_PASS=dupersuper
      - BACKUP02_SNAPSHOT_NAME=var_local
      - BACKUP02_SNAPSHOT_PATH=/rootfs/var/local/data
      - BACKUP02_SNAPSHOT_EXCLUDE=restic/*,service/*
      - BACKUP02_SNAPSHOT_BEGIN=+10
      - BACKUP02_INTERVAL=60
    networks:
      - services
    restart: always

networks:
  services:
    external: true