#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="rclone"
prepare_service 20-restic

check_container_initialized
check_service_initialized init

transform_var file \
                    RCLONE_ARGS
liftoff

print_start "Starting Rclone ${R_CLONE_VERSION}"
exec /usr/sbin/rclone \
                        ${RCLONE_ARGS}
